import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Foundation",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode;}>) {
  const cookieStore = await cookies()
  const sessionCookie = cookieStore.get("session")?.value

  let user:{
    id: number,
    name: string,
    role: string
  } | null = null;
  
  if(sessionCookie) {
    try {
      user = JSON.parse(sessionCookie)
    } catch {
      user = null;
    }
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="flex">
          <Navbar user={user}/>
          <main className="min-h-screen w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}